namespace DnDCampaignManager.Api.Services;

// SRD 5.1 Equipment, pages 64–69. Prices converted to gp; weights in lb.
// A dash in the source weight column is represented as zero (negligible weight).
// See docs/items.md for source links and attribution.
public static class SrdItemCatalog
{
    public const string Source = "SRD 5.1 (modified)";
    public sealed record StarterItem(string Name, string Category, decimal CostGp, decimal WeightLb, string Description = "");
    public static readonly StarterItem[] Items =
    [
        new("Club", "Weapon", 0.1m, 2),
        new("Dagger", "Weapon", 2, 1),
        new("Greatclub", "Weapon", 0.2m, 10),
        new("Handaxe", "Weapon", 5, 2),
        new("Javelin", "Weapon", 0.5m, 2),
        new("Light hammer", "Weapon", 2, 2),
        new("Mace", "Weapon", 5, 4),
        new("Quarterstaff", "Weapon", 0.2m, 4),
        new("Sickle", "Weapon", 1, 2),
        new("Spear", "Weapon", 1, 3),
        new("Light crossbow", "Weapon", 25, 5),
        new("Dart", "Weapon", 0.05m, 0.25m),
        new("Shortbow", "Weapon", 25, 2),
        new("Sling", "Weapon", 0.1m, 0),
        new("Battleaxe", "Weapon", 10, 4),
        new("Flail", "Weapon", 10, 2),
        new("Glaive", "Weapon", 20, 6),
        new("Greataxe", "Weapon", 30, 7),
        new("Greatsword", "Weapon", 50, 6),
        new("Halberd", "Weapon", 20, 6),
        new("Lance", "Weapon", 10, 6),
        new("Longsword", "Weapon", 15, 3),
        new("Maul", "Weapon", 10, 10),
        new("Morningstar", "Weapon", 15, 4),
        new("Pike", "Weapon", 5, 18),
        new("Rapier", "Weapon", 25, 2),
        new("Scimitar", "Weapon", 25, 3),
        new("Shortsword", "Weapon", 10, 2),
        new("Trident", "Weapon", 5, 4),
        new("War pick", "Weapon", 5, 2),
        new("Warhammer", "Weapon", 15, 2),
        new("Whip", "Weapon", 2, 3),
        new("Blowgun", "Weapon", 10, 1),
        new("Hand crossbow", "Weapon", 75, 3),
        new("Heavy crossbow", "Weapon", 50, 18),
        new("Longbow", "Weapon", 50, 2),
        new("Net", "Weapon", 1, 3),
        new("Padded", "Armor", 5, 8),
        new("Leather", "Armor", 10, 10),
        new("Studded leather", "Armor", 45, 13),
        new("Hide", "Armor", 10, 12),
        new("Chain shirt", "Armor", 50, 20),
        new("Scale mail", "Armor", 50, 45),
        new("Breastplate", "Armor", 400, 20),
        new("Half plate", "Armor", 750, 40),
        new("Ring mail", "Armor", 30, 40),
        new("Chain mail", "Armor", 75, 55),
        new("Splint", "Armor", 200, 60),
        new("Plate", "Armor", 1500, 65),
        new("Shield", "Armor", 10, 6),
        new("Backpack", "Adventuring gear", 2, 5),
        new("Bedroll", "Adventuring gear", 1, 7),
        new("Bell", "Adventuring gear", 1, 0),
        new("Blanket", "Adventuring gear", 0.5m, 3),
        new("Candle", "Adventuring gear", 0.01m, 0),
        new("Crowbar", "Adventuring gear", 2, 5),
        new("Grappling hook", "Adventuring gear", 2, 4),
        new("Hammer", "Adventuring gear", 1, 3),
        new("Healer's kit", "Adventuring gear", 5, 3),
        new("Hunting trap", "Adventuring gear", 5, 25),
        new("Hooded lantern", "Adventuring gear", 5, 2),
        new("Bullseye lantern", "Adventuring gear", 10, 2),
        new("Mess kit", "Adventuring gear", 0.2m, 1),
        new("Oil (flask)", "Adventuring gear", 0.1m, 1),
        new("Piton", "Adventuring gear", 0.05m, 0.25m),
        new("Pouch", "Adventuring gear", 0.5m, 1),
        new("Rations (1 day)", "Adventuring gear", 0.5m, 2),
        new("Hempen rope (50 feet)", "Adventuring gear", 1, 10),
        new("Silk rope (50 feet)", "Adventuring gear", 10, 5),
        new("Shovel", "Adventuring gear", 2, 5),
        new("Tinderbox", "Adventuring gear", 0.5m, 1),
        new("Torch", "Adventuring gear", 0.01m, 1),
        new("Waterskin", "Adventuring gear", 0.2m, 5, "Listed weight assumes a full waterskin."),
        new("Whetstone", "Adventuring gear", 0.01m, 1)
    ];
}
